### Register a new user
POST http://localhost:5203/api/auth/register
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "Password123!"
}

### Login with that user
POST http://localhost:5203/api/auth/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "Password123!"
}

### Get current user (protected)
GET http://localhost:5203/api/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiZW1haWwiOiJ0ZXN0QGV4YW1wbGUuY29tIiwiZXhwIjoxNzY2NTIxMzYzLCJpc3MiOiJFcXVhdGhvcmFBUEkiLCJhdWQiOiJFcXVhdGhvcmFDbGllbnQifQ.mBM6DQ6Mvrkp7JfVy4M_qSSoobbi87iaiW7qciozx6I